---
- name: Reset admin password on Cisco IOS/IOS-XE devices
  hosts: ios_devices
  gather_facts: no
  vars:
    new_password: "{{ new_password }}"

  tasks:
    - name: Reset admin user password on IOS/IOS-XE
      ios_config:
        lines:
          - username admin privilege 15 secret 0 {{ new_password }}
        save_when: modified

    - name: Verify the new password on IOS/IOS-XE
      ios_command:
        commands:
          - show running-config | include username
      register: ios_output

    - name: Display username configuration on IOS/IOS-XE
      debug:
        var: ios_output.stdout_lines

- name: Reset admin password on Cisco IOS-XR devices
  hosts: iosxr_devices
  gather_facts: no
  vars:
    new_password: "{{ new_password }}"

  tasks:
    - name: Reset admin user password on IOS-XR
      xr_config:
        lines:
          - username admin secret {{ new_password }}
        commit: yes

    - name: Verify the new password on IOS-XR
      xr_command:
        commands:
          - show running-config | include username
      register: iosxr_output

    - name: Display username configuration on IOS-XR
      debug:
        var: iosxr_output.stdout_lines
