---
- name: Install GCC
  ansible.builtin.dnf:
    name: gcc
    state: present

- name: Install GCC Toolset
  ansible.builtin.dnf:
    name: 'https://dl.rockylinux.org/pub/rocky/9/devel/x86_64/os/Packages/g/gcc-toolset-12-build-12.0-6.el9.x86_64.rpm'
    state: present
...